version: '3.9'
services:
  redis:
    container_name: redis
    volumes:
    - ./data:/data
    image: redis:latest
    command: redis-server --save 60 1 --loglevel warning --requirepass rescale
    ports:
    - 6379:6379
    restart: always